# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\layout42.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(475, 290)
        MainWindow.setMinimumSize(QtCore.QSize(475, 290))
        MainWindow.setMaximumSize(QtCore.QSize(475, 290))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelHeader = QtWidgets.QLabel(self.centralwidget)
        self.labelHeader.setGeometry(QtCore.QRect(10, 0, 161, 31))
        self.labelHeader.setObjectName("labelHeader")
        self.buttonGo = QtWidgets.QPushButton(self.centralwidget)
        self.buttonGo.setGeometry(QtCore.QRect(370, 220, 91, 31))
        self.buttonGo.setDefault(True)
        self.buttonGo.setObjectName("buttonGo")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 51, 222))
        self.layoutWidget.setObjectName("layoutWidget")
        self.layoutBirth = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.layoutBirth.setContentsMargins(0, 0, 0, 0)
        self.layoutBirth.setObjectName("layoutBirth")
        self.birth = QtWidgets.QLabel(self.layoutWidget)
        self.birth.setObjectName("birth")
        self.layoutBirth.addWidget(self.birth)
        self.B0 = QtWidgets.QCheckBox(self.layoutWidget)
        self.B0.setObjectName("B0")
        self.layoutBirth.addWidget(self.B0, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.B1 = QtWidgets.QCheckBox(self.layoutWidget)
        self.B1.setObjectName("B1")
        self.layoutBirth.addWidget(self.B1, 0, QtCore.Qt.AlignHCenter)
        self.B2 = QtWidgets.QCheckBox(self.layoutWidget)
        self.B2.setObjectName("B2")
        self.layoutBirth.addWidget(self.B2, 0, QtCore.Qt.AlignHCenter)
        self.B3 = QtWidgets.QCheckBox(self.layoutWidget)
        self.B3.setChecked(True)
        self.B3.setObjectName("B3")
        self.layoutBirth.addWidget(self.B3, 0, QtCore.Qt.AlignHCenter)
        self.B4 = QtWidgets.QCheckBox(self.layoutWidget)
        self.B4.setObjectName("B4")
        self.layoutBirth.addWidget(self.B4, 0, QtCore.Qt.AlignHCenter)
        self.B5 = QtWidgets.QCheckBox(self.layoutWidget)
        self.B5.setObjectName("B5")
        self.layoutBirth.addWidget(self.B5, 0, QtCore.Qt.AlignHCenter)
        self.B6 = QtWidgets.QCheckBox(self.layoutWidget)
        self.B6.setObjectName("B6")
        self.layoutBirth.addWidget(self.B6, 0, QtCore.Qt.AlignHCenter)
        self.B7 = QtWidgets.QCheckBox(self.layoutWidget)
        self.B7.setObjectName("B7")
        self.layoutBirth.addWidget(self.B7, 0, QtCore.Qt.AlignHCenter)
        self.B8 = QtWidgets.QCheckBox(self.layoutWidget)
        self.B8.setObjectName("B8")
        self.layoutBirth.addWidget(self.B8, 0, QtCore.Qt.AlignHCenter)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(70, 30, 51, 222))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.layoutSurvival = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.layoutSurvival.setContentsMargins(0, 0, 0, 0)
        self.layoutSurvival.setObjectName("layoutSurvival")
        self.survival = QtWidgets.QLabel(self.layoutWidget1)
        self.survival.setObjectName("survival")
        self.layoutSurvival.addWidget(self.survival)
        self.S0 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.S0.setObjectName("S0")
        self.layoutSurvival.addWidget(self.S0, 0, QtCore.Qt.AlignHCenter)
        self.S1 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.S1.setObjectName("S1")
        self.layoutSurvival.addWidget(self.S1, 0, QtCore.Qt.AlignHCenter)
        self.S2 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.S2.setChecked(True)
        self.S2.setObjectName("S2")
        self.layoutSurvival.addWidget(self.S2, 0, QtCore.Qt.AlignHCenter)
        self.S3 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.S3.setChecked(True)
        self.S3.setObjectName("S3")
        self.layoutSurvival.addWidget(self.S3, 0, QtCore.Qt.AlignHCenter)
        self.S4 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.S4.setObjectName("S4")
        self.layoutSurvival.addWidget(self.S4, 0, QtCore.Qt.AlignHCenter)
        self.S5 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.S5.setObjectName("S5")
        self.layoutSurvival.addWidget(self.S5, 0, QtCore.Qt.AlignHCenter)
        self.S6 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.S6.setObjectName("S6")
        self.layoutSurvival.addWidget(self.S6, 0, QtCore.Qt.AlignHCenter)
        self.S7 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.S7.setObjectName("S7")
        self.layoutSurvival.addWidget(self.S7, 0, QtCore.Qt.AlignHCenter)
        self.S8 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.S8.setObjectName("S8")
        self.layoutSurvival.addWidget(self.S8, 0, QtCore.Qt.AlignHCenter)
        self.sliderFPS = QtWidgets.QSlider(self.centralwidget)
        self.sliderFPS.setGeometry(QtCore.QRect(140, 40, 271, 22))
        self.sliderFPS.setMinimum(1)
        self.sliderFPS.setMaximum(500)
        self.sliderFPS.setSingleStep(1)
        self.sliderFPS.setProperty("value", 15)
        self.sliderFPS.setOrientation(QtCore.Qt.Horizontal)
        self.sliderFPS.setObjectName("sliderFPS")
        self.labelFPS = QtWidgets.QLabel(self.centralwidget)
        self.labelFPS.setGeometry(QtCore.QRect(140, 20, 71, 16))
        self.labelFPS.setObjectName("labelFPS")
        self.sliderUpdate = QtWidgets.QSlider(self.centralwidget)
        self.sliderUpdate.setGeometry(QtCore.QRect(140, 90, 271, 22))
        self.sliderUpdate.setMinimum(1)
        self.sliderUpdate.setMaximum(100)
        self.sliderUpdate.setProperty("value", 5)
        self.sliderUpdate.setOrientation(QtCore.Qt.Horizontal)
        self.sliderUpdate.setObjectName("sliderUpdate")
        self.labelUpdate = QtWidgets.QLabel(self.centralwidget)
        self.labelUpdate.setGeometry(QtCore.QRect(140, 70, 81, 16))
        self.labelUpdate.setObjectName("labelUpdate")
        self.boxX = QtWidgets.QSpinBox(self.centralwidget)
        self.boxX.setGeometry(QtCore.QRect(140, 190, 42, 22))
        self.boxX.setMinimum(3)
        self.boxX.setMaximum(256)
        self.boxX.setProperty("value", 48)
        self.boxX.setObjectName("boxX")
        self.boxY = QtWidgets.QSpinBox(self.centralwidget)
        self.boxY.setGeometry(QtCore.QRect(200, 190, 42, 22))
        self.boxY.setMinimum(3)
        self.boxY.setMaximum(256)
        self.boxY.setProperty("value", 48)
        self.boxY.setObjectName("boxY")
        self.labelX = QtWidgets.QLabel(self.centralwidget)
        self.labelX.setGeometry(QtCore.QRect(140, 170, 41, 16))
        self.labelX.setObjectName("labelX")
        self.labelY = QtWidgets.QLabel(self.centralwidget)
        self.labelY.setGeometry(QtCore.QRect(200, 170, 41, 16))
        self.labelY.setObjectName("labelY")
        self.boxPadding = QtWidgets.QSpinBox(self.centralwidget)
        self.boxPadding.setGeometry(QtCore.QRect(260, 190, 42, 22))
        self.boxPadding.setMaximum(127)
        self.boxPadding.setProperty("value", 12)
        self.boxPadding.setObjectName("boxPadding")
        self.labelPadding = QtWidgets.QLabel(self.centralwidget)
        self.labelPadding.setGeometry(QtCore.QRect(260, 170, 47, 13))
        self.labelPadding.setObjectName("labelPadding")
        self.boxSparsity = QtWidgets.QSpinBox(self.centralwidget)
        self.boxSparsity.setGeometry(QtCore.QRect(320, 190, 42, 22))
        self.boxSparsity.setMinimum(0)
        self.boxSparsity.setMaximum(100)
        self.boxSparsity.setProperty("value", 4)
        self.boxSparsity.setObjectName("boxSparsity")
        self.labelSparsity = QtWidgets.QLabel(self.centralwidget)
        self.labelSparsity.setGeometry(QtCore.QRect(320, 170, 47, 13))
        self.labelSparsity.setObjectName("labelSparsity")
        self.labelCellSize = QtWidgets.QLabel(self.centralwidget)
        self.labelCellSize.setGeometry(QtCore.QRect(140, 120, 81, 16))
        self.labelCellSize.setObjectName("labelCellSize")
        self.sliderCellSize = QtWidgets.QSlider(self.centralwidget)
        self.sliderCellSize.setGeometry(QtCore.QRect(140, 140, 271, 22))
        self.sliderCellSize.setMinimum(5)
        self.sliderCellSize.setMaximum(64)
        self.sliderCellSize.setProperty("value", 16)
        self.sliderCellSize.setOrientation(QtCore.Qt.Horizontal)
        self.sliderCellSize.setInvertedAppearance(False)
        self.sliderCellSize.setInvertedControls(False)
        self.sliderCellSize.setObjectName("sliderCellSize")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(120, 30, 20, 221))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.labelFPSVal = QtWidgets.QLabel(self.centralwidget)
        self.labelFPSVal.setGeometry(QtCore.QRect(430, 40, 31, 21))
        self.labelFPSVal.setFrameShape(QtWidgets.QFrame.Box)
        self.labelFPSVal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.labelFPSVal.setObjectName("labelFPSVal")
        self.labelUpdateVal = QtWidgets.QLabel(self.centralwidget)
        self.labelUpdateVal.setGeometry(QtCore.QRect(430, 90, 31, 21))
        self.labelUpdateVal.setFrameShape(QtWidgets.QFrame.Box)
        self.labelUpdateVal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.labelUpdateVal.setObjectName("labelUpdateVal")
        self.labelCellSizeVal = QtWidgets.QLabel(self.centralwidget)
        self.labelCellSizeVal.setGeometry(QtCore.QRect(430, 140, 31, 21))
        self.labelCellSizeVal.setFrameShape(QtWidgets.QFrame.Box)
        self.labelCellSizeVal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.labelCellSizeVal.setObjectName("labelCellSizeVal")
        self.buttonReset = QtWidgets.QPushButton(self.centralwidget)
        self.buttonReset.setGeometry(QtCore.QRect(140, 220, 41, 31))
        self.buttonReset.setObjectName("buttonReset")
        self.checkStartPaused = QtWidgets.QCheckBox(self.centralwidget)
        self.checkStartPaused.setGeometry(QtCore.QRect(190, 220, 81, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkStartPaused.sizePolicy().hasHeightForWidth())
        self.checkStartPaused.setSizePolicy(sizePolicy)
        self.checkStartPaused.setObjectName("checkStartPaused")
        self.labelRestoreFileVal = QtWidgets.QLabel(self.centralwidget)
        self.labelRestoreFileVal.setGeometry(QtCore.QRect(10, 260, 351, 20))
        self.labelRestoreFileVal.setFrameShape(QtWidgets.QFrame.Box)
        self.labelRestoreFileVal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.labelRestoreFileVal.setText("")
        self.labelRestoreFileVal.setObjectName("labelRestoreFileVal")
        self.buttonRestoreFile = QtWidgets.QPushButton(self.centralwidget)
        self.buttonRestoreFile.setGeometry(QtCore.QRect(370, 260, 91, 21))
        self.buttonRestoreFile.setObjectName("buttonRestoreFile")
        self.checkCellGrid = QtWidgets.QCheckBox(self.centralwidget)
        self.checkCellGrid.setGeometry(QtCore.QRect(290, 220, 61, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkCellGrid.sizePolicy().hasHeightForWidth())
        self.checkCellGrid.setSizePolicy(sizePolicy)
        self.checkCellGrid.setObjectName("checkCellGrid")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Game of Life Rule Menu"))
        self.labelHeader.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Game of Life Rule Menu</span></p></body></html>"))
        self.buttonGo.setText(_translate("MainWindow", "Go"))
        self.birth.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Birth</p></body></html>"))
        self.B0.setText(_translate("MainWindow", "0"))
        self.B1.setText(_translate("MainWindow", "1"))
        self.B2.setText(_translate("MainWindow", "2"))
        self.B3.setText(_translate("MainWindow", "3"))
        self.B4.setText(_translate("MainWindow", "4"))
        self.B5.setText(_translate("MainWindow", "5"))
        self.B6.setText(_translate("MainWindow", "6"))
        self.B7.setText(_translate("MainWindow", "7"))
        self.B8.setText(_translate("MainWindow", "8"))
        self.survival.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Survival</p></body></html>"))
        self.S0.setText(_translate("MainWindow", "0"))
        self.S1.setText(_translate("MainWindow", "1"))
        self.S2.setText(_translate("MainWindow", "2"))
        self.S3.setText(_translate("MainWindow", "3"))
        self.S4.setText(_translate("MainWindow", "4"))
        self.S5.setText(_translate("MainWindow", "5"))
        self.S6.setText(_translate("MainWindow", "6"))
        self.S7.setText(_translate("MainWindow", "7"))
        self.S8.setText(_translate("MainWindow", "8"))
        self.labelFPS.setText(_translate("MainWindow", "Maximum FPS"))
        self.labelUpdate.setText(_translate("MainWindow", "Update interval"))
        self.labelX.setText(_translate("MainWindow", "<html><head/><body><p>X Count</p></body></html>"))
        self.labelY.setText(_translate("MainWindow", "<html><head/><body><p>Y Count</p></body></html>"))
        self.labelPadding.setText(_translate("MainWindow", "Padding"))
        self.labelSparsity.setText(_translate("MainWindow", "Sparsity"))
        self.labelCellSize.setText(_translate("MainWindow", "Cell size"))
        self.labelFPSVal.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.labelUpdateVal.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.labelCellSizeVal.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.buttonReset.setText(_translate("MainWindow", "Reset"))
        self.checkStartPaused.setText(_translate("MainWindow", "Start Paused"))
        self.buttonRestoreFile.setText(_translate("MainWindow", "Restore File..."))
        self.checkCellGrid.setText(_translate("MainWindow", "Cell Grid"))

